import Head from 'next/head'
import Link from 'next/link';
export default function Home({ data }) {
  // const router = useRouter()
  // const onClick =(id) => {
  //   router.push(`/person/${id}`)
  // }
  return (
    <>
      <Head>
        <title>Practice It All~</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <div className='container'>
        {data.map((movie) => (
          <Link href={`/person/${movie.id}`} key={movie.id}
          
          >
            {/* <div onClick={()=>onClick(movie.id) }> */}
            <div>
              <img src={movie.squareImage ? movie.squareImage : null} />
              <h4>{movie.name}</h4>
              <span>{Math.floor(movie.netWorth)}</span>
              <span> Billion</span>
              <span> / {movie.industries}</span>
            </div>
          </Link>
        ))}
      </div>
      <style jsx>{`
        .container {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 10px;
          padding: 20px;
          background-color: darkgrey;
        }
        .container img {
          width: 250px;
          height: 250px;
        }
      `}</style>
    </>
  );
}


export async function getServerSideProps() {
  const data = await (await fetch(` https://billions-api.nomadcoders.workers.dev/`)).json()
    return {
      props: {
        data:data
      }
    }
}

